/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package inicial;

import javax.swing.JOptionPane;

/**
 *
 * @author danielortanapoleon
 */
public class FormSoporte extends javax.swing.JFrame {

    /**
     * Creates new form FormSoporte
     */
    public FormSoporte() {
        
        initComponents();
        this.setLocationRelativeTo(null);
        txt_modulo.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btn_volver = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txt_modulo = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        combo_modulo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(223, 236, 230));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(33, 90, 109));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Trash Hunters");

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Bienvenido al Soporte tecnico de MAR");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(245, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(275, 275, 275))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(240, 240, 240))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 110));

        jPanel3.setBackground(new java.awt.Color(60, 162, 162));

        jLabel4.setText(" ©2024 TrashHunters - MAR");

        btn_volver.setBackground(new java.awt.Color(146, 199, 163));
        btn_volver.setFont(new java.awt.Font("Helvetica Neue", 1, 16)); // NOI18N
        btn_volver.setForeground(new java.awt.Color(255, 255, 255));
        btn_volver.setText("Volver");
        btn_volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_volverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 441, Short.MAX_VALUE)
                .addComponent(btn_volver, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel4)
                .addContainerGap(31, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_volver)
                .addContainerGap())
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 800, 80));

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel5.setText("Soporte tecnico");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 6, -1, -1));

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        jLabel6.setText("Contacta a un desarrollador para solucionar el problema:");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 54, -1, -1));

        jLabel7.setText("Telefono celular: 52 56 2383 5203");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 560, -1));

        jLabel10.setText("Ayudanos indicando el modulo en el que se encuentra el error para darle una mejor solucion:");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 560, -1));

        jLabel12.setText("Correoel ectronico: trashhunters.mar.soporte@gmail.com");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, 340, -1));

        txt_modulo.setForeground(new java.awt.Color(204, 204, 204));
        txt_modulo.setText("Ingrese el modulo....");
        txt_modulo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_moduloFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_moduloFocusLost(evt);
            }
        });
        txt_modulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_moduloMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txt_moduloMouseEntered(evt);
            }
        });
        txt_modulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_moduloActionPerformed(evt);
            }
        });
        jPanel4.add(txt_modulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 550, -1));

        jButton2.setBackground(new java.awt.Color(147, 199, 163));
        jButton2.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Enviar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 100, 40));

        combo_modulo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Modulo Inicio (Problemas al iniciar el sistema)", "Modulo de Seleccion de usuario (Problemas al seleccionar el tipo de usuario)", "Modulo de Usuario (Problemas con la pagina web)", "Modulo de Trabajador (Problemas al insertar el reporte o visualizar datosdatos)", "Modulo de Ingreso de administrador (Problemas al validar cuanta de Administrador", "Modulo de Administrador (Problemas al guardar, insertar, modificar o mostrar)", "Modulo de Clave (Problemas al validar la homoclave)", "Modulo de Creacion de cuanta (No se creo la cuanta de administrador)", "Otro" }));
        combo_modulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_moduloActionPerformed(evt);
            }
        });
        jPanel4.add(combo_modulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 550, -1));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 590, 280));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_moduloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_moduloActionPerformed
    }//GEN-LAST:event_txt_moduloActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        String modulo=combo_modulo.getSelectedItem().toString();
        String otro=txt_modulo.getText();
            if(modulo.equalsIgnoreCase("Seleccionar")){
                
                 JOptionPane.showMessageDialog(null, "Debe de seleccionar un modulo");
                 
             }else{
                
                if(otro.equalsIgnoreCase("Otro")){
                    
                    JOptionPane.showMessageDialog(null, "Especifique el m odulo en el campo de texto");
                    txt_modulo.setVisible(true);
                    
                }else{
                    
                    combo_modulo.setVisible(false);
                    txt_modulo.setVisible(false);
                    CQuejas objetoQuejas = new CQuejas();
                    objetoQuejas.RegistroQuejas(txt_modulo);
                    FormQuejaGuardad objetoGuardar = new FormQuejaGuardad();
                    objetoGuardar.setVisible(true);
                    this.dispose();
            }
            }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btn_volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_volverActionPerformed
        FormInicios objetoInicio = new FormInicios();
        objetoInicio.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_volverActionPerformed

    private void txt_moduloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_moduloMouseClicked
        txt_modulo.setText("");
        txt_modulo.setForeground(new java.awt.Color(0, 0, 0));
    }//GEN-LAST:event_txt_moduloMouseClicked

    private void txt_moduloFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_moduloFocusLost
       
    }//GEN-LAST:event_txt_moduloFocusLost

    private void txt_moduloFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_moduloFocusGained
      
    }//GEN-LAST:event_txt_moduloFocusGained

    private void txt_moduloMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_moduloMouseEntered
        
    }//GEN-LAST:event_txt_moduloMouseEntered

    private void combo_moduloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_moduloActionPerformed

        String modulo=combo_modulo.getSelectedItem().toString();
        txt_modulo.setText(modulo);

    }//GEN-LAST:event_combo_moduloActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormSoporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormSoporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormSoporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormSoporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormSoporte().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_volver;
    private javax.swing.JComboBox<String> combo_modulo;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField txt_modulo;
    // End of variables declaration//GEN-END:variables
}
